source/archives.html.erb, source/author.html.erb, source/category.html.erb, source/index.html.erb, source/layouts/blog.erb
=> Adjust Article Date Format

Gemfile.lock
Compassのバージョンアップ。
内容は下記のもの。
[Support Ruby 2.2.0 by tonytonyjan · Pull Request #1903 · Compass/compass](https://github.com/Compass/compass/pull/1903)
=> $ bundle update

source/posts/2015-01-16-wordpress-to-middleman.html.md
#46 読んでて気になったところをちょこっと直してみました。
良かったら Merge してくだせぃ @dkimura
=> Middleman移行記事の軽微な修正

README.md
=> Fix description of deployment

data/author.yml
http://tech.feedforce.jp/member/
hszmtmhr さんはゲストライターなので一覧の一番下にもってきた。
=> Fix members order

.tachikoma.yml, README.md
https://github.com/feedforce/feedforce-ruboty に引き続き、こちらも http://tachikoma.io/ を使った継続的bundle updateを始めます。
PRがマージされたら私の方で tachikoma.io に追加します。
=> Add setting tachikoma.io

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5968924231925547153">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150205021418

README.md
ここまで英語で書かなくて良い気もするけど :santa: 
なお英作文に自信なし。。
=> Update description of Automatically `$ bundle update`

source/css/fftt.sass
Syntax Highlightのスタイルを修正するためのPRです。
=> Fix inline `code` Style

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5981608014988773760">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150312021435

source/posts/2014-07-31-agile_whiteboards.md, source/posts/2014-10-17-jenkins-server-ci.md
https://github.com/feedforce/site-cookbooks を https://github.com/feedforce/ff-cookbooks にリネームしたので、過去記事にも反映しました。
=> Add P.S. to the article 2014-10-17-jenkins-server-ci

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5984144774002950893">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150319021440

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5986681535338841983">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150326021446

source/css/fftt.sass
1行目がずれるので修正してみました。自信ナッシングです。
http://tech.feedforce.jp/serverci-by-docker.html
=> Fix code style

source/css/fftt.sass
広げてみた
https://github.com/feedforce/tech.feedforce.jp/pull/89#issuecomment-102915124
修正前↓
修正後↓
リスト全体的に行間広がってますが個人的には許容範囲かなと...
というかなんでこんなにリスト系のスタイル複雑なん…？:(；ﾞﾟ'ωﾟ'):
=> 本文中のリストの行間

source/partials/_footer.erb
http://www.ptengine.jp/
上記のヒートマップツールを試験導入するためのPRです。
```html
<script type="text/javascript">
window._pt_sp_2 = [];
_pt_sp_2.push('setAccount,76baed57');
var _protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
(function() {
var atag = document.createElement('script'); atag.type = 'text/javascript'; atag.async = true;
atag.src = _protocol + 'js.ptengine.jp/pta.js';
var stag = document.createElement('script'); stag.type = 'text/javascript'; stag.async = true;
stag.src = _protocol + 'js.ptengine.jp/pts.js';
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(atag, s);s.parentNode.insertBefore(stag, s);
})();
</script>
```
=> Ptengineの使用感を確かめるために解析コードを追加した

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6012047808503947287">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150604021150

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6017121236705100161">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150618021152

source/posts/2015-07-06-startup-terraform.html.md
余計な行があったので、削除します。恥ずかしい＞＜
セルフマージします。
=> Delete unnecessary comment

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6024731381662527820">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6024731381662527820">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20150709021155

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6032341528723574435">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6032341528723574435">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20150730021200

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6042488388064451226">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6042488388064451226">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20150827021211

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6045025097855751439">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6045025097855751439">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20150903021205

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6050098494070422385">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6050098494070422385">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20150917021159

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6052635201753319236">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6052635201753319236">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20150924021202

.tachikoma.yml
=> Remove .tachikoma.yml

source/posts/2015-12-23-aws-lambda.html.md
内定者エンジニアによる技術ブログ記事執筆の第2弾の記事になります！
今回はAWSのAPI GatewayとLambda, DynamoDBを使ってSlackボットを作りました。
~~記事自体はこれでほぼ完成ですが、githubのリンク先のコードがまだ未完成になっていますのでそちらはこの後対応予定です :bow:~~
ひとまずコードを[otofu-square/lgtm_bot](https://github.com/otofu-square/lgtm_bot)にプッシュしました！
確認していただける状態になっていると思います。
誤字脱字、説明が不足している箇所、蛇足な箇所等何でもご指摘ください！
よろしくお願いします。
=> API Gateway + LambdaでSlackボットを作ってみた

app.json
HerokuのReview appsが動かなくなったと聞いて頑張ってみる。
設定初期で作成される `app.json` から作りなおしたらどうなるのかなっていう実験。
悪化したらすみません。:pray:
=> remove app.json

source/css/fftt.sass, source/index.html.erb
> https://feedforce.slack.com/archives/tech-blog/p1456217729000106
>
> やっぱり read more 的なリンク欲しいな…(´・ω・`)
を見てガッと追加した。
なお、美術は 5 段階評価でずっと 2 でした。
=> Add '続きを読む' on root page

Gemfile, Gemfile.lock, circle.yml, script/contribution-ranking.rb
origin/master にマージされた時、記事が追加または変更があった時だけ、Slack に投稿数ランキングを出すようにしてみました。 #tech-blog に通知が出ています。
こういうのどうですかね？
=> Slack Contribution Ranking

script/contribution-ranking.rb, source/posts/2016-09-27-mackerel-go-plugin-delayed-job.html.md
#215 のランキングトリガーが間違っていたので直しました。動作確認のため、人為的に(?)トリガーを発行させます。
CI 通ったらセルフマージします。
=> Fix ranking trigger

source/posts/2015-09-10-roadworker.html.md
=> Fix typo in roadworker article

data/author.yml
```
_   _ _       _ _
| | (_|_)     (_|_)
| |_ _ _ _ __  _ _ _ __
| __| | | '_ \| | | '_ \
| |_| | | | | | | | | | |
\__| |_|_| |_| |_|_| |_|
_/ |      _/ |
|__/      |__/
```
```
_ _    _
| | |  (_)
__| | | ___ _ __ ___  _   _ _ __ __ _
/ _` | |/ / | '_ ` _ \| | | | '__/ _` |
| (_| |   <| | | | | | | |_| | | | (_| |
\__,_|_|\_\_|_| |_| |_|\__,_|_|  \__,_|
```
=> Forever tjinjin and dkimura !!!

data/author.yml
本人が殿堂入り申請するのも恥ずかしいですが… 😳 
よろしくお願いします。
=> t-nakano を殿堂入りにする

Gemfile, Gemfile.lock
ローカルで動かそうとしたら上手く動かなかったので（主に puma）、
雑に bundle update します。
=> Bundle update manually
